### ISSUE TITLE
Упрощение требований-выражений

### ISSUE THREAD

**Issue by agievich** [bcryptoregulatory/skzi-requirements#1]
Требования представлены в виде логических выражений, связанных кванторами И (запятая) и ИЛИ. Одно логическое выражение может быть частью другого (вложение через круглые скобки). Логические выражения, окаймленные квадратными скобками, могут опускаться. Элементарные логические выражения -- это требования из таблицы 1. Вот такой формализм.

Если мы имеем дело с логическими выражениями, то естественно поставить вопрос об их упрощении. Чем проще требования, тем лучше для всех. 

Рассмотрим выражение `УС2 или (УС2, УС5)` из таблицы 2. Его можно преобразовать в `УС2, [УС5]`. Что означает `[УС5]`? Что можно реализовать `УС5`. А можно и не реализовывать. Требование `УС5` фактически не выдвигается. Его можно исключить и тогда `УС2 или (УС2, УС5)` упрощается до `УС2`.

Я привел пример многоступенчатого упрощения. Других подобных примеров в таблице 2 я не нашел. Но с опциональными требованиями нужно навести порядок. Формально это не требования, и их можно исключить. Тогда почти весь последний столбец пропадает (кстати,  требования по форматам неожиданно перестали выдвигаться). Видимо все-таки не таков был замысел. Наверное каждое опциональное требование следует сопроводить пометкой о том, при каких условиях он становится обязательным.

**Comment by zm1ca** [comment]
`УС2 или (УС2, УС5)` появилось, скорее всего, в ходе редакторских правок, ещё до введения обозначения [ ] и действительно выбивается из общей логики, спасибо. 

На данный момент опциональные требования имеют служат для отображения возможностей по созданию разнообразных продуктов, с сохранением приемлемого уровня требований в зависимости от использования или игнорирования тех или иных функций. То есть мы не хотим убирать УС5 (Атрибутные сертификаты) совсем, как в приведённом вами примере, а выдвигать или не выдвигать требование уже по факту использования соответствующего механизма. Это же касается и форматов: мы хотим оставить наглядной возможность использования форматов и не отрывать их от таблицы (чтобы не уменьшить их значимость и упростить формирование заявки для тех, кому форматы нужны), при этом мы столкнулись с рядом примеров СКЗИ, где поддержание форматов действительно не требуется.

Вряд ли мы станем комментировать каждое опциональное требование, однако, полагаю, стоит поискать способ лаконично пояснить наш подход к ним в примечаниях (либо как-то реструктурировать саму таблицу, разделив на обязательную и опциональную части).

**Comment by NikGomel** [comment]
> Формально это не требования, и их можно исключить. Тогда почти весь последний столбец пропадает (кстати, требования по форматам неожиданно перестали выдвигаться).

Требования к формату предъявляются в примечании  таблице 2 пункт 5. Где сказано, что при взаимодействии информационных систем требования к форматам обязательно.

**Comment by zm1ca** [comment]
Вопрос упрощения требований рассмотрен и учтён (0bdedcc3bc9b6ad4e8229f950a49fe98905c759a). Понятие опционального требования дополнительно затронуто в #5 и частично изменено (87e92dfe01a734fafec42212968265dd6649968b). Однако, по видимому, оно требует дальнейшей доработки параллельно с внесением прочих изменений.
