### ISSUE TITLE
Генерация ключей

### ISSUE THREAD

**Issue by enigmaby** [bcryptoregulatory/skzi-requirements#15]
Предлагаем при генерации личных ключей включить в обязательном порядке только требование УГ1 (псевдослучайный  датчик в это требование включен в соответствии с п.5.6 СТБ.34.101.27), а УГ2 исключить из требований, так как считаем, что с использованием только псевдослучайного датчика сгенерировать криптографически стойкий ключ невозможно.

**Comment by zm1ca** [comment]
> с использованием только псевдослучайного датчика сгенерировать криптографически стойкий ключ невозможно

Данный факт не подвергается сомнению, однако мы не ставим целью данной таблицы установление строгих ограничений к ГСЧ/ГПСЧ. Это связано с тем, что всякий ключ предназначен для использования в каком-либо криптографическом алгоритме, описанном в некотором стандарте. В этом же стандарте содержатся требования по генерации соответствующих ключей, продиктованные целью применения ключа. 

Кроме того, мы считаем допустимыми обоснованные решения по построению СКЗИ, при которых качественная энтропия погружается в средство снаружи (например, она может вырабатываться на другом сертифицированном СКЗИ, и передаваться с соблюдением требований по транспорту ключевой информации). 

Выражаем готовность рассмотреть конструктивную критику озвученных позиций.

**Comment by NikGomel** [comment]
> Предлагаем при генерации личных ключей включить в обязательном порядке только требование УГ1

Не все программные средства выработки ЭЦП имеют в своем составе хорошие источники случайности, а в большинстве случаев их вообще нет. Поэтому использование ГПСЧ решает эту проблему.

**Comment by zm1ca** [comment]
Согласно СТБ 34.101.45 в качестве личных ключей подписи могут быть использованы ключи, полученные с помощью ГПСЧ, следовательно возможно использования средства генерации личных ключей по назначению с механизмом УГ2.

**кроме того:**
` мы считаем допустимыми обоснованные решения по построению СКЗИ, при которых качественная энтропия погружается в средство снаружи.`
