### ISSUE TITLE
Средства управления открытыми ключами

### ISSUE THREAD

**Issue by enigmaby** [bcryptoregulatory/skzi-requirements#16]
Считаем, что требования "Средства выработки ЭЦП" и "Средства проверки ЭЦП" избыточны, в виду того, что сертификаты могут не использоваться при построении прикладных систем. Кроме того в Законе об электронном документе и в СТБ 34.101.45 требования к составу ЭЦП (выработка, проверка, генерация личных и открытых ключей подписи) не предусматривают средства управления открытыми ключами.

**Comment by zm1ca** [comment]
Выдвигаемые требования к указанным Вами классам СКЗИ основаны на том, что нами проводится сертификация средств, имеющих дело с юридически значимыми ЭЦП, см. п.4 Примечаний к таблице 2:
> 4. Средства выработки ЭЦП, средства проверки ЭЦП, средства генерации личных и открытых ключей и криптографический токен являются средством ЭЦП соответствии с Законом Республики Беларусь от 28 декабря 2009 года "Об электронном документе и электронной цифровой подписи" (Национальный реестр правовых актов Республики Беларусь, 2010 г., N 15, 2/1665).

Мы обратили внимание на данную проблему и готовы рассмотреть более конкретные предложения.

**Comment by zm1ca** [comment]
В ходе внутреннего обсуждения была принята позиция: опциональность использования сертификатов учтена с помощью обозначения `[ ]` в Таблице 2. Кроме того, возможно использование средств контроля целостности, не предполагающее издание сертификатов.
