### ISSUE TITLE
Требования к средствам линейного шифрования

### ISSUE THREAD

**Issue by enigmaby** [bcryptoregulatory/skzi-requirements#17]
Предлагаем исключить из требования к Средствам линейного шифрования при использовании схемы с Требованиями к криптографическим протоколам и управления ключами "УГ1 или УГ2" исключить из Требований к криптографическим алгоритмам "АХ1 или АХ2", оставив только требование "АШИ".

**Comment by zm1ca** [comment]
Предоставленная формулировка требует дополнительных пояснений. Возможно, речь об `АИ1 или АИ2`? Если речь об `*УГ1 или УГ2, АХ1 или АХ2`, то алгоритмы хэширования здесь указаны в связи с требованием СТБ 34.101.27 СЧ.6. Предложение будет рассматриваться, однако приветствуется его дополнение обоснованиями.

**Comment by agievich** [comment]
Если в `*УГ1 или УГ2, АХ1 или АХ2` подразумевается (снова возвращаемся к вопросу #2 об интерпретации требований!), что `АХ1 или АХ2` нужно для криптографической постобработки при генерации СЧ, то `АХ1 или АХ2` следует исключить:
- способов постобработки может быть много и, таким образом, связка `АХ1 или АХ2` не является обязательной;
- постобработка не нужна, если выбрана опция `УГ2`.
