### ISSUE TITLE
Средства генерации личных и открытых ключей

### ISSUE THREAD

**Issue by agievich** [bcryptoregulatory/skzi-requirements#20]
Название "Средства генерации личных и открытых ключей для средств ЭЦП" не очень удачно. Во-первых, "средства для средств". Во-вторых, пары ключей могут использоваться не только в алгоритмах ЭЦП, но еще и в алгоритмах транспорта (УК5), в протоколах (ПФ1).

Предлагаю сократить: ""Средства генерации личных и открытых ключей".

**Comment by NikGomel** [comment]
Предложение принимается. Но название, скорее всего, будет соответствовать Закону «Об электронном документе и электронной цифровой подписи», а именно «средство выработки личного ключа или открытого ключа»;
