### ISSUE TITLE
ИТТАС: Предложение 5: Изменить профиль для средства линейного шифрования с ПФ5.

### ISSUE THREAD

**Issue by Alex-ITTAS** [bcryptoregulatory/skzi-requirements#23]
Ранее в #9 уже обсуждался профиль с ПФ5, но обсуждение было закрыто по непонятным нам причинам. Считаем, что обсуждение стоит продолжить.
Сейчас имеется профиль
УГ1 или УГ2, ПФ1 или УК5, УС2, УСЗ или УС4, [ПФЗ], [ПФ5]
Считаем, что такой профиль некорректен по следующей причине. 
По текущим требованиям ПФ5 нельзя использовать без ПФ1 (BSTS или BMQV) или УК5 (транспорт ключа). Но, например, в средствах, реализующих vpn с криптонаборами DHE, не нужны протоколы ПФ1 или транспорт ключа УК5. 
**Предлагаем** писать ПФ5 через ИЛИ: 
УГ1 или УГ2, ПФ1 или ПФ5 или ...

**Comment by NikGomel** [comment]
ПФ5 предлагается оставить таблице 2 как необязательные, для того чтобы поддержать совместимость со старыми продуктами. Данные криптонаборы разрабатывались специально для протокола TLS. Целесообразность их использования как отдельных алгоритмов предлагается обсудить с @agievich.

**Comment by agievich** [comment]
Строчка 
```
УГ1 или УГ2, ПФ1 или УК5, УС2, УСЗ или УС4, [ПФЗ], [ПФ5]
```
мне кажется нелогичной. Она может быть раскрыта и вот так: ``... ПФ1, ПФ3...`` и вот так ``...УК5, ПФ3, ПФ5,...`` и еще многими разными способами.

Поддерживаю предложение
```
УГ1 или УГ2, ПФ1 или ПФЗ или ПФ5 или УК5, УС2, УСЗ или УС4
```

**Comment by saverchenko** [comment]
Мы тоже согласны с последним предложением:
УГ1 или УГ2, ПФ1 или ПФЗ или ПФ5 или УК5, УС2, УСЗ или УС4
