### ISSUE TITLE
Изменение формата таблиц

### ISSUE THREAD

**Issue by zm1ca** [bcryptoregulatory/skzi-requirements#24]
Поскольку одним из приоритетов при переработке таблиц является сокращение их объёма, выносятся на рассмотрение следующие предложение (которые следует рассматривать как независимые и требующие доработки и обсуждения):
1. Таблица 1 упраздняется
2. Удаляется столбец с требованиями к безопасности, а информация из него переносится в примечания.
3. Аналогично п.3 удаляется столбец с форматами данных
4. Обозначения в таблице 2 заменяются на другие, содержащие непосредственную ссылку на стандарт, например:

|Средства криптографической защиты информации | Требования к криптографическим алгоритмам | Требования к криптографическим протоколам и управлению ключами | 
| --- | --- | --- | 
| Средства предварительного шифрования | (31 (пп. 6.3 или 6.4 или 6.5), 31 (6.6) или 47 (6.1)) или 31 (6.7)| \*27 (5.6) или 47 (6.2 или 6.3), 31 (7.2) или 45 (7.2, Б1 или Б2 или Б3, Д)| 

_Относительно п.4 запрашиваются предложения по обозначениям, упрощающим восприятие таблиц._

**Comment by agievich** [comment]
Не следует привязываться к пунктам стандартов. Стандарты меняются, пункты плывут. Скоро будет запущено обсуждение новой редакции СТБ 34.101.31. Совсем другие пункты.

В новых редакциях стандартов мы, наоборот, отвязываемся от пунктов, делаем ставку на имена (`belt-ecb`, `bign-sign`, etc.). Понятно, что это можно сделать не всегда, у некоторых механизмов нет имен. В связи с этим таблица 1 имеет важно значение. Она фактически создает `namespace`, покрывая собственными именами  имена и пункты стандартов.

Кроме этого, таблица 1 систематизирует криптографические механизмы, демонстрирует ассортимент криптографических "кирпичиков".

А вот таблица 2 действительно спорная. Здесь также проводится систематизация, но уже не "кирпичиков", а "зданий". Систематизация "типов зданий" полезна, но вот предпринятая систематизация "проектов" уже спорна.

**Comment by agievich** [comment]
Упрощение Таблицы 2 (объединение столбцов, упразднение последнего столбца) поддерживаю.

**Comment by zm1ca** [comment]
> Кроме этого, таблица 1 систематизирует криптографические механизмы, демонстрирует ассортимент криптографических "кирпичиков".

Согласен. Кроме того, чтобы разобраться в том, какие же механизмы требуется реализовать в средстве в случае отказа от Таблицы 1, придётся иметь под рукой чуть ли не все стандарты (или запоминать, какой пункт какого стандарта означает какой механизм).

**Comment by zm1ca** [comment]
Полагаю, снизить необходимость в переходах между таблицами 1 и 2 можно изменив обозначения на более осмысленные. Так, например, замена обозначений: AШ = belt, AИ1 = belt-mac, АИ2 = hmac, АШИ - belt-datawrap, УГ = rng, УК1 = keyrep, УК5 = keytransport, ПФ3 = bsts-bmqv, УС2 = x509, УС3 = crl, УС4 = ocsp, Б1 = sotfware, Б2 = hardware, Ф1 = enveloped, приведёт к следующему виду профиля для средств предварительного шифрования:

|Средства криптографической защиты информации | Требования к криптографическим алгоритмам | Требования к криптографическим протоколам и управлению ключами | Требования безопасности | Требования к форматам данных |
| --- | --- | --- | --- | --- |
| Средства предварительного шифрования | (belt, belt-mac или hmac) или belt-datawrap | \*rng, keyrep или keytransport| sotfware или hardware | [enveloped] |
| | | rng, bsts-bmqv или keytransport, x509, crl или ocsp|

Порог вхождения для понимания такой таблицы снижается до минимального, то есть ориентирования в международных названиях криптографических механизмов.

**Comment by agievich** [comment]
В целом поддерживаю. Мы систему имен (namespace) давно продвигаем. Считаем, что без имен (слов) трудно и разговаривать, и создавать нормативные документы.  Получаются сплошные бюрократизмы в стиле "п. 6.9 СТБ 34.101.31-2011". 

"То, что не названо, -- не существует."

Детали:
1. Желательно снабжать каждое имя префиксом, который указывает на стандарт: `cms-signed`, `belt-keyrep`. Больше ясности и единообразия. Возможные префиксы: `belt`, `bign`, `brng`, `bels`, `bash`, `bake`, `btok`, `bpki`, а также вот здесь: https://github.com/bcrypto/stb/blob/master/README.md.
2. Мы стали сокращать имена: `belt-dwp` вместо `belt-datawrap`, `bign-keyt`  вместо `bign-keytransport`. Желательно учесть.

**Comment by zm1ca** [comment]
Прошу всех ознакомиться с [новым видением таблиц](https://github.com/bcryptoregulatory/skzi-requirements/blob/verbal-based-approach/skzi-requirements.md). Упор сделан на возможность понимания маршрутов с минимальной необходимостью переключаться между несколькими таблицами, а также минимальной привязкой к пунктам стандартов.

Даже если у вас нет конкретных предложений по улучшению данной таблицы, убедительно прошу **высказать своё мнение здесь**, в любой форме (будь то лайк, комментарий с оценкой или review запроса на слияние веток). В сущности, данный репозиторий создан не только для решения проблем, но и для поиска наиболее удобных решений.

**Comment by agievich** [comment]
Шаги по унификации имен:
- software -> skzi-sw;
- hardware -> skzi-hw;
- belt -> belt-encr или belt-modes;
- bign-with-hbelt -> bign-sign (без детализации фх; фх дополнительно детализируется в таблице 2);
- hmac -> brng-hmac (для единообразия, первая лексема всегда указывает на стандарт);
- bash -> bash-hash (в стандарте bash будут еще другие алгоритмы);
- 1176-dsa -> stb1176-sign;
- tls -> btls;
- dhX-XXX -> btls-dhX-XXX;
- brng разделить на skzi-rng и brng (с возможной допонительной детализацией brng-ctr, brng-hmac);
- revoke-req -> bpki-revoke-req или просто bpki-revoke;
- crl -> x509-crl (можно объяснить, что требуется дополнительное профилирование в соответствии с bpki или дополнительно ввести bpki-crl);
- signed -> cms-signed;
- enveloped -> cms-enveloped.

**Comment by zm1ca** [comment]
Принято в https://github.com/bcryptoregulatory/skzi-requirements/commit/9d2fde659986d8a230f32f43dad8032ea600a758 за исключением:
- software -> skzi-sw; (нужно обладать специфическими знаниями, чтобы разобраться что имелось ввиду)
- hardware -> skzi-hw;
- dhX-XXX -> btls-dhX-XXX; (алгоритмов много, и перечисляются они через запятую. изменение этих обозначений раздует таблицу)
- brng разделить на skzi-rng и brng (разделение убрано ранее для лаконичности. в любом случае, требования устанавливаются стандартами, а не профилями)
