### ISSUE TITLE
Требование [Ф2] не входит в область применения средств предварительного шифрования

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#34]
К средствам предварительного шифрования выдвигается [Ф2], которое связано только с шифрованием сообщений, обмениваемых с компонентами ИОК, что не входит в область применения средств предварительного шифрования

**Comment by andrewkostevich** [comment]
Требование [Ф2] сужает требования СТБ 34.101.23 - оставляет только KeyTransRecipientInfo и запрещает остальные типы, в частности тип KEKRecipientInfo, который как раз предназначен для средств предварительного шифрования с предварительно распределенным ключом (обращаю внимание, что данный тип СПШ упоминается в примечании 3 к приказу) - требование [Ф2] должно быть исключено из требований к средствам предварительного шифрования, так как не попадает в область применения СПШ и сужает виды СПШ, в том числе запрещая СПШ с предварительно распределенным ключом

**Comment by zm1ca** [comment]
Модернизация ИОК будет проводиться с упором на СТБ 34.101.78-2019. Следовательно, если данный стандарт умышленно ограничивает использование СПШ с предварительно распределенным ключом в рамках ИОК -- так и должно быть. В то же время, использование средств указанного типа в ИОК регулируется (в отношении форматов) механизмом Ф1, не запрещающим использование `KEKRecipientInfo`.
