### ISSUE TITLE
Избыточные требования к алгоритмам криптографического токена

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#35]
В столбце с требованиями к криптографическим алгоритмам средства указывают только алгоритмы, которые предоставляются пользователю в качестве сервиса: в случае криптографического токена алгоритмы АШ и АИ1 пользователю не предоставляются и носят внутренний служебный характер

**Comment by zm1ca** [comment]
Поддерживаю. Возникает вопрос также и по алгоритмам хэширования в средствах выработки, поверки ЭЦП и токенах. Все ли сертифицированные средства этих классов способны предоставить пользователю возможность вычислить хэш?

upd. перенос темы хешей в #44

**Comment by zm1ca** [comment]
В ходе обсуждения по #45 вновь возник вопрос о том, как классифицировать алгоритм шифрования (основным или служебным), если основной или одной из ключевых функций устройства (средства защиты НСД + криптографический токен) является хранение информации в зашифрованном виде. Если новый маршрут будет создан, необходимо обеспечить последовательность в принятии решений в обоих указанных случаях.
