### ISSUE TITLE
Неполная ссылка на BPACE в ПА1

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#36]
В СТБ 34.101.79 BPACE не определяется, BPACE описан в СТБ 34.101.66,

**Comment by zm1ca** [comment]
Действительно, в 79 стандарте протокол скорее профилирован. Следуя логике описания механизмов Ф1 и Ф2 (в редакции #41 ), предлагаю определить ПА1 в виде:

`ПА1 | парольная аутентификация по протоколу ВРАСЕ | СТБ 34.101.66-2014 (п. 7.6 раздела 7), СТБ 34.101.79-2019 (п. 8.3 раздела 8)`
