### ISSUE TITLE
Убрать иностранные криптографические алгоритмы из требования ПИ

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#37]
Ссылка на СТБ 34.101.21 в полном объеме включает ссылку на иностранные криптографические алгоритмы

**Comment by andrewkostevich** [comment]
Раздел 12 стандарта включает описание механизмов для **37** иностранных криптографических алгоритмов, включение в пункт ПИ требований стандарта в полном объеме является некорректным

**Comment by zm1ca** [comment]
Необходимо всесторонне оценить сложившуюся ситуацию и выработать варианты решений. Если у Вас есть конкретные предложения -- с интересом рассмотрим в ближайшее время.
