### ISSUE TITLE
Требование [Ф2] для криптографического токена неоднозначно

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#38]
Требования по форматам средств выработки ЭЦП и токенов должны совпадать: требование [Ф2] для средств выработки ЭЦП нет, следовательно не должно быть и у токенов

**Comment by zm1ca** [comment]
Согласен. Полагаю, это связано с #35 и наличием механизма АШ (в текущей редакции).
