### ISSUE TITLE
Отсутствие программно-аппаратных средств выработки ЭЦП

### ISSUE THREAD

**Issue by zm1ca** [bcryptoregulatory/skzi-requirements#4]
В предложениях и вопросах по требованиям к СКЗИ неоднократно был поднят вопрос об отсутствии программно-аппаратных средств выработки ЭЦП. 

Пояснение: в качестве программно-аппаратных средств выработки ЭЦП предлагается использовать СКЗИ класса **криптографические токены**.

Данная позиция вызвала ряд вопросов, поэтому предлагается для предметной критики/обсуждения здесь.

**Comment by NikGomel** [comment]
Предлагается средства выработки ЭЦП разделить на два подкласса:
1. программные средства выработки ЭЦП.
2. криптографический токен (программно-аппаратное средство выработки ЭЦП)

**Comment by agievich** [comment]
"Средство выработки ЭЦП" -- это стабильный класс СКЗИ, с которого собственно все и начиналось (см. первый Закон об ЭЦП). Считаю, что не следует сужать класс до программных средств.Криптографические токены в стиле BTOK -- это не просто средства ЭЦП. Это и дополнительный функционал, и достаточно жесткая архитектура.

Считаю, что лучше выделить 2 блока (строки): программные средства (с Б1) и аппаратные (аппаратно-программные, программно-аппаратные) средства (с Б2 и без УЗ1, УЗ2).
