### ISSUE TITLE
Необходимость Ф1 и Ф3

### ISSUE THREAD

**Issue by zm1ca** [bcryptoregulatory/skzi-requirements#40]
Встаёт вопрос о статусе требований Ф1 и Ф3, в связи с тем что они:
1. Дублированы в Ф2 и Ф4
2. Содержатся в квадратных скобках

Выходит, что в случае, когда они обязательны (то есть в рамках ИОК), становятся актуальными требования Ф2 и Ф4, поглощающие их.

**предлагается**: убрать Ф1 и Ф3 и передать их названия механизмам Ф2 и Ф4 соответственно (.т.к. они более ёмкие)

**Comment by andrewkostevich** [comment]
Вопрос интерпретации требований Ф2 и Ф4: требования Ф2 и Ф4 **сужают** область действия Ф1  и Ф3 (см. обсуждение в #34 для Ф2) - исключение Ф1 и Ф3 нецелесообразно

**Comment by zm1ca** [comment]
Да, сужают, описывая применение в рамках PKI. Но если мы не требуем соблюдать данные форматы вне PKI, нужны ли нам "широкие", но необязательные механизмы? Необходимость профилирования, конечно, больше касается формата подписанных данных. Что касается формата конвертованных данных, в каких случаях это требования можно предъявлять как обязательное.

**Comment by zm1ca** [comment]
Отвечая на свой вопрос: возможно действительно нужны, поскольку требования в квадратных скобках обязательны не в рамках PKI, но и в рамках межведомственного взаимодействия.
