### ISSUE TITLE
Защита контейнера при условии

### ISSUE THREAD

**Issue by andrewkostevich** [bcryptoregulatory/skzi-requirements#43]
Требование УЗ2 включает СТБ 34.101.78-2019 (пп. 11.2-11.5 раздела 11). Если посмотреть на п. 11.1  СТБ 34.101.78-2019 то можно видеть, что требование по разделению секрета для ключевого контейнера является условным, так как есть два варианта

1.  Аппаратная защита контейнера на носителе ключевой информации 

> Чтобы сохранить стойкость личного ключа при хранении, контейнер должен дополнительно защищаться аппаратно. Например, контейнер может храниться внутри устройства, доступ к объектам которого осуществляется только после предъявления пароля, причем доступ блокируется после нескольких неверных попыток ввода пароля. Для сравнения: блокировать ввод пароля при прямом доступе к контейнеру нельзя

2 . Защита контейнера с использованием разделения секрета

> Если дополнительная защита контейнера затруднена, то вместо низкоэнтропийного
пароля следует использовать высокоэнтропийный ключ... Ключ защиты следует
разделить на несколько частичных секретов с помощью алгоритма, определенного в СТБ
34.101.60

Текущая редакция требований является безусловной - выбрасывает п. 1.

По тексту п.11.1 СТБ 34.101.78-2019 применение разделения секрета является условным (`Если ... то`), данную условность следует отразить в требованиях.

Как вариант, УЗ1, УЗ2 заменить на `УЗ - СТБ 34.101.78-2019 (пп. 11.1-11.5 раздела 11)`

**Comment by zm1ca** [comment]
Да, такая безусловность была создана умышленно, поскольку требование УЗ2 предъявляется только к программным средствам выработки ЭЦП. Разработчикам предлагается использовать разделение секрета, чтобы решить вопрос защиты ключа с помощью разрабатываемого средства, а не перекладывать эту задачу на аппаратную платформу, в которой функционирует программа. Ближайший пример -- телефон, механизмы безопасности которого не сертифицируются, не всегда конкретизируются разработчиком и могут отличаться на различных моделях.

**Comment by Siarhei-St** [comment]
Следует учесть вариант, когда для аппаратной защиты контейнера приведенной в п.11.1 СТБ 34.101.78-2019 используется сертифицированный аппаратный носитель ключевой информации. В этом случае все используемые механизмы безопасности описаны и компетентно проверены. 
Т.о. поддерживаю предложение andrewkostevich :
"Как вариант, УЗ1, УЗ2 заменить на УЗ - СТБ 34.101.78-2019 (пп. 11.1-11.5 раздела 11)"

**Comment by zm1ca** [comment]
Да, доверить аппаратную защиту сертифицированному средству было бы возможно. Нужно продумать как учесть данный случай, но при этом не допустить злоупотребления (как в примере с телефоном). Готовы рассмотреть более компромиссные предложения.

**Comment by andrewkostevich** [comment]
Предложения в #45

**Comment by zm1ca** [comment]
Предлагается принять изменения частично: УЗ2 изложить в виде` СТБ 34.101.78-2019 (раздел 11), СТБ 34.101.45-2013 (приложение Е)`. Программное СКЗИ может осуществлять аппаратные методы защиты, при условии соблюдения требования ЗО.5 СТБ 34.101.27-2011. Парольная же защита должна быть обеспечена с применением СТБ 34.101.45-2013 (приложение Е), с учётом требований п.11.1 СТБ  34.101.78-2019 и ИА.5 (качество секретов аутентификации) СТБ 34.101.27-2011. 

Требование использовать алгоритм belt-keywrap явным образом не выдвигается в п.11.1 СТБ  34.101.78-2019. Сделано ли это умышленно, то есть допускает ли модель угроз использование проприетарных алгоритмов -- актуальный вопрос к @agievich. 

Таким образом, предлагается не сертифицировать  `аппаратный носитель ключевой информации` (предлагаемый в #45), однако допускать использование таких носителей для обеспечения защиты объектов, при наличии доказательств соответствия ТНПА в части физической безопасности.

**Comment by Siarhei-St** [comment]
Возникает на мой взгляд противоречие. С одной стороны мы готовы "доверить аппаратную защиту сертифицированному средству", с другой стороны не определяя в "Профилях"  требования через набор ТНПА взаимосвязанных с ТехРегламентом к данному средству защиты информации, мы не позволяем разработчикам создать сертифицированный на соответствие  ТехРегламенту защищенный аппаратный носитель с конкретными и проверяемыми механизмами безопасности, использующими криптографические методы защиты.

**Comment by agievich** [comment]
> Требование использовать алгоритм belt-keywrap явным образом не выдвигается в п.11.1 СТБ 34.101.78-2019.

Выдвигается: см. последний абзац пункта.

**Comment by zm1ca** [comment]
> Выдвигается: см. последний абзац пункта.

В таком случае, считаю возможным внести изменения #49 и закрыть данный вопрос. Что касается вопроса доказательства доверенности аппаратного носителя -- обсуждение де-факто перенесено в  #45 , где предложен вариант решения данной проблемы путём введения нового маршрута сертификации для специализированных средств.
