### ISSUE TITLE
Связка АП2 + АХ1 или АХ2

### ISSUE THREAD

**Issue by zm1ca** [bcryptoregulatory/skzi-requirements#44]
В ряде маршрутов используется связка `АП2, АХ1 или АХ2`. Стоит рассмотреть вопрос целесообразности включения `АХ1 или АХ2`:
1. АП2 включает belt-hash (АХ1) как вспомогательный алгоритм.
2. Вряд ли алгоритмы хеширования предоставляются пользователю как сервисы.
3. Возможно, включение АХ2 было временной мерой (на этапе формирования таблицы).

**Comment by zm1ca** [comment]
Кроме того, можно перенести "или" в механизмы, создав
`АХ | хэширование по алгоритму belt-hash или bash | СТБ 34.101.31-2011 (п. 6.9 раздела 6) или 
СТБ 34.101.77-2016 (1=128 или 1=192 или 1=256)`

**Comment by zm1ca** [comment]
Требования к алгоритмам хеширования включены для конкретизации выбора h, поскольку требования п. 5.5 хоть и включают в себя слова `функция h должна быть алгоритмически определена в ТНПА` не видятся нам достаточными на данный момент.

**Comment by NikGomel** [comment]
Предлагаю убрать алгоритм хэширования из средств проверки и выборки ЭЦП, так как он не предоставляется как сервис.
