### ISSUE TITLE
Схожие маршруты

### ISSUE THREAD

**Issue by zm1ca** [bcryptoregulatory/skzi-requirements#5]
На данный момент существует два маршрута требований к криптографическим протоколам и управлению ключами для криптографических токенов:
- `УГ1 или УГ2, ПА1, ПИ, УК1, УК2, УКЗ, УК4, УК5, УС1, УС2`
- `УГ1 или УГ2, ПА1, ПА2, ПИ, УК1, УК2, УКЗ, УК4, УК5, УС1, УС2, УС7`

Первый вариант создан как замена программно-аппаратным средствам выработки ЭЦП (см [issue #4](https://github.com/bcryptoregulatory/skzi-requirements/issues/4)), а второй - для ID карт, и по этой причине имеет дополнительные требования `ПА2` и `УС7`.

предложение: в соответствии с [issue #2](https://github.com/bcryptoregulatory/skzi-requirements/issues/2) уменьшить "профильность" маршрутов и объединить их в `УГ1 или УГ2, ПА1, ПИ, УК1, УК2, УКЗ, УК4, УК5, УС1, УС2, [ПА2, УС7]` и сместить акцент в логике использования обозначения [ ] с "необязательности требования" на  "способ сокращения ветвления маршрутов"

**Comment by NikGomel** [comment]
Первый маршрут предназначен для выработки ЭЦП на localhost.
Второй маршрут предназначен для возможности выработки ЭЦП в терминальном режиме, т.е. на удаленном host.

**Comment by zm1ca** [comment]
Предлагается следующая редакция примечаний к Таблице 2 (с учётом ранее озвученного предложения):

> Примечания:
> 1. В таблице 2 используются условные обозначения криптографических механизмов, определённые в Таблице 1.
> 2. Условные обозначения, которые указаны в круглых скобах, реализуются совместно. Квадратные скобки содержат требования, носящие рекомендательный характер, за исключением случаев, указанных в пп.5-6.
> 3. Символом \* обозначены наборы требований к криптографическим протоколам и управлению ключами предъявляемые к СКЗИ, в которых секреты предварительно распределены.
> 4. Средства выработки ЭЦП, средства проверки ЭЦП, средства генерации личных и открытых ключей и криптографический токен являются средством ЭЦП соответствии с Законом Республики Беларусь от 28 декабря 2009 года &quot;Об электронном документе и электронной цифровой подписи&quot; (Национальный реестр правовых актов Республики Беларусь, 2010 г., N 15, 2/1665).
> 5. Для СКЗИ, обеспечивающих взаимодействие информационных систем, требования к форматам данных являются обязательными.
> 6. При необходимости использовать СКЗИ "Криптографический токен" в терминальном режиме в соответствии с СТБ 34.101.79, требования ПА2 и УС7 являются обязательными.
> 7. Требования к форматам данных Ф6 и Ф7 необходимо выполнять при взаимодействии СКЗИ с соответствующими службами инфраструктуры открытых ключей.
> 8. Требования к управлению ключами УС6 должно выполняться при реализации СКЗИ процедуры отзыва сертификата открытого ключа.
