### ISSUE TITLE
Предлагается создать профиль требований для УЦ и РЦ

### ISSUE THREAD

**Issue by NikGomel** [bcryptoregulatory/skzi-requirements#50]
К УЦ и РЦ будут предъявляться требования определенные Приказом ОАЦ от 29.11.2013 №89

**Comment by zm1ca** [comment]
Требований к РЦ можно добиться объединением маршрутов средств выработки, проверки ЭЦП и генерации ключей, так что данный маршрут плохо ложится в логику таблицы как отдельный.

**Comment by zm1ca** [comment]
Текущее предложение от @NikGomel реализованное в #51 

|Средства криптографической защиты информации | Требования к криптографическим алгоритмам | Требования к криптографическим протоколам и управлению ключами | Требования безопасности | Требования к форматам данных |
| --- | --- | --- | --- | --- |
| Удостоверяющий центр | (АШ, АИ1 или АИ2) или АШИ, АП2, АХ1, АХ2  | УГ, ПТ, УЗ1, УК3, УК4, УС1, УС2, УС3, УС4, УС5, [УС6], [УС7] | Б2  | [Ф2], [Ф4] |
| Регистрационный центр | АП2, АХ1, АХ2 | УГ, УК3, УК4, УС1, УС2, УС3, УС4, УС5 | Б2 |

**Comment by agievich** [comment]
Разве УЦ и РЦ -- это СКЗИ? Думаю, что нет. Это системы, построенные с использованием СКЗИ.

**Comment by NikGomel** [comment]
Данные требования вынесены для предъявления  к лицензиатам, оказывающим услуги по распространению открытых ключей, а также аккредитации поставщиков ГосСУОК, чтобы их не указывать в Приказах ОАЦ.
