### ISSUE TITLE
Требования к терминалу 

### ISSUE THREAD

**Issue by NikGomel** [bcryptoregulatory/skzi-requirements#55]
|Средства криптографической защиты информации | Требования к криптографическим алгоритмам | Требования к криптографическим протоколам и управлению ключами | Требования безопасности | Требования к форматам данных |
| --- | --- | --- | --- | --- |
| Терминал взаимодействия с криптографическим токеном | АШ, АИ1 | УГ, УК1, ПФ2, УС7 | Б1, Б2  |       |

**Comment by zm1ca** [comment]
Реализовано в приказе. Будет актуализировано в #56
