### ISSUE TITLE
ИТТАС:Предложение 1: Добавить новые механизмы DHE_BIGN, DHT_BIGN согласно СТБ 34.101.65-2014 (п.п. B.2.5.1, B.2.5.2).

### ISSUE THREAD

**Issue by Alex-ITTAS** [bcryptoregulatory/skzi-requirements#7]
**Предлагается** в таблицу 1 в дополнение к ПФ4 (алгоритм DHE_PSK_BIGN) и ПФ5 (алгоритм DHT_PSK_BIGN) добавить новые механизмы формирования общего ключа: ПФ6 – формирование общего ключа по алгоритму DHE_BIGN согласно СТБ 34.101.65-2014 (п. B.2.5.1); ПФ7 - формирование общего ключа по алгоритму DHT_BIGN согласно СТБ 34.101.65-2014 (п. B.2.5.2).

**Обоснование.** 
Многие разработчики реализовали VPN с поддержкой национальной криптографии. Для VPN есть внутренний стандарт, который определяет, что формирование общего ключа и аутентификация сторон должна выполняться таким же образом, как и в протоколе TLS. При этом другие механизмы VPN отличаются от TLS. В связи с этим, для сертификации VPN необходимо в дополнение к алгоритмам DHE_PSK_BIGN и DHT_PSK_BIGN добавить механизмы, соответствующие алгоритмам формирования общего ключа DHE_BIGN и DHT_BIGN.

**Comment by zm1ca** [comment]
Данное предложение учтено и обсуждается как часть #9. Соответствующие механизмы добавлены в b1bcdc01e054092cd96d0202a831d23fb7bdef3a.
