### ISSUE TITLE
ИТТАС:Предложение 3: Изменить профиль для средства линейного шифрования с необязательными протоколами ПФЗ, ПФ4.

### ISSUE THREAD

**Issue by Alex-ITTAS** [bcryptoregulatory/skzi-requirements#9]
Для средств линейного шифрования строку с требованиями
            УГ1 или УГ2, ПФ1 или УК5, УС2, УСЗ или УС4, [ПФЗ], [ПФ4]
**предлагаем** заменить на строку
     УГ1 или УГ2, ПФ1 или ПФЗ или ПФ5 или ПФ6 или ПФ7 или УК5, УС2, УСЗ или УС4.

**Обоснование.**
По текущим требованиям в средстве линейного шифрования одновременно может использоваться ПФ1 (формирование общего ключа по протоколам BSTS и BMQV) и, например, ПФ4 (протокол DHE_PSK_BIGN). Не совсем понятно, почему при этом ПФ1 должен быть обязательно, а ПФ4 – необязательно. Более того, протокол ПФ4 не требует сертификатов и их проверки (согласно СТБ 34.101.65), а в указанной строчке сертификаты и их проверка обязательна (указано УС2, УСЗ или УС4). В то же время протокол ПФ5 требует использования сертификатов. Также предлагается разрешить использование протоколов ПФ6 (алгоритм DHE_BIGN согласно п. B.2.5.1 СТБ 34.101.65-2014) и ПФ7 (алгоритм DHT_BIGN согласно п. B.2.5.2 СТБ 34.101.65-2014), которые требуют использования сертификатов и их проверки. В связи с вышесказанным предлагаем писать:
      УГ1 или УГ2, ПФ1 или ПФЗ или ПФ5 или ПФ6 или ПФ7 или УК5, УС2, УСЗ или УС4.

**Comment by NikGomel** [comment]
Допущена опечатка, требования ПФ4 и ПФ5 поменяем местами. Поддерживается предложение о расширении криптонаборов. В требования ПФ5 можем включить следующие криптонаборы DHT_PSK_BIGN или DHT_BIGN или DHE_BIGN, или добавить их отдельно как  ПФ6 и ПФ7. Но они будут иметь необязательный характер.

**Comment by Alex-ITTAS** [comment]
Считаем, что для лаконичности профилей лучше в ПФ5 включить криптонаборы DHT_PSK_BIGN или DHT_BIGN или DHE_BIGN.
Не совсем понятно, что значит "Но они будут иметь необязательный характер". Считаем, что ПФ5 нужно писать через ИЛИ. Иначе получится, что ПФ1 или УК5 нужно обязательно реализовывать, а ПФ5 дополнительно. Но в vpn с криптонаборами DHE не нужны протоколы ПФ1 или транспорт ключа УК5. В случае включения в ПФ5 дополнительных протоколов профиль можно указать следующим образом:
УГ1 или УГ2, ПФ1 или ПФЗ или ПФ5 или УК5, УС2, УСЗ или УС4.
Не совсем понятна целесообразность включения в данный профиль ПФ3. Протокол Диффи-Хеллмана используется как вспомогательный в криптонаборах DHE. Для протокола Диффи-Хеллмана есть отдельный профиль. Возможно, следует дополнить отдельный профиль для протокола Диффи-Хеллмана требованиями по сертификатам и их проверке и исключить его из данного профиля, тогда получим:
УГ1 или УГ2, ПФ1 или ПФ5 или УК5, УС2, УСЗ или УС4.

**Comment by zm1ca** [comment]
> Не совсем понятна целесообразность включения в данный профиль ПФ3.

Предложение добавить ПФ3 было внесено S-Terra (к обсуждению целесообразности приглашается @saverchenko), с целью обеспечить совместимость с ранее выпущенным оборудованием. По аналогии с Вашими предложениями добавить криптонаборы в качестве отдельных механизмов, данное требование было добавлено как рекомендательное (в соответствии с п.2 Примечаний к Таблице 2).

> Иначе получится, что ПФ1 или УК5 нужно обязательно реализовывать, а ПФ5 дополнительно.

Да, на данный момент логика именно такая. 

> Но в vpn с криптонаборами DHE не нужны протоколы ПФ1 или транспорт ключа УК5. 

Замечание учтено, однако внесение предложенных изменений откладывается т.к. требуется дополнительная проработка и обсуждения.

**Comment by zm1ca** [comment]
> Допущена опечатка, требования ПФ4 и ПФ5 поменяем местами.

> Считаем, что для лаконичности профилей лучше в ПФ5 включить криптонаборы DHT_PSK_BIGN или DHT_BIGN или DHE_BIGN.


Соответствующие изменения внесены b1bcdc01e054092cd96d0202a831d23fb7bdef3a

**Comment by NikGomel** [comment]
ПФ4 и ПФ5 предлагается оставить  таблице 2 как необязательные, для того чтобы поддержать совместимость со старыми продуктами. Данные криптонаборы разрабатывались специально для протокола TLS.  Целесообразность их использования как отдельных алгоритмов предлагается обсудить с @agievich.
